### ISSUE TITLE
Add documentation for training

### ISSUE THREAD

**Issue by dreamflasher** [cybertronai/imagenet18#27]
How do you split/sort the data for training? It says that you train on the smaller images first, are they sorted by increasing filesize, or are they grouped?

**Comment by yaroslavvb** [comment]
They are randomly shuffled, but image resolution changes.
You can see the schedule here -- https://github.com/cybertronai/imagenet18/blob/master/train.py#L82
Few epochs with 128x128 images, then switch to 224x224, then 288x288

**Comment by dreamflasher** [comment]
Ah thank you very much, that's very helpful!
